{{- if .Values.ingressClass.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ include "cloudflare-tunnels-operator.ingressClassName" . }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: {{ .Values.ingressClass.isDefaultClass | quote }}
spec:
  controller: cloudflare-tunnels-operator.io/ingress-controller
{{- end -}}
