---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflared-example-credentials
stringData:
  credentials.json: '{}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflared-example-origin-cert
stringData:
  cert.pem: ''
